#!/bin/bash
. /var/openpanel/api/sh/module.sh

SSLDIR=/etc/ssl/private
LIGHTTPDIR=/etc/lighttpd/conf-enabled

TomcatAdmin.update() {
  appid=tomcat
  newpass=$(coreval TomcatAdmin password)
  awstats=$(coreval TomcatAdmin awstatspass)
  [ -z "${awstats}" ] || authd runscript openapp-call "awstats" passwd "${awstats}"
  if [ ! -z ${newpass} ]; then
    authd runscript openapp-call "$appid" passwd "$newpass"

    restart_tomcat
  fi
}

HTTPS.delete() {
	authd deletefile ${SSLDIR}/tomcat.pem
	authd deletefile ${LIGHTTPDIR}/ssl.conf

	restart_lighttpd
}

HTTPS.create() {
	SSLCERT=$(coreval HTTPS pem)

cat <<EOB > $(pwd)/tomcat.pem
${SSLCERT}
EOB

/var/openpanel/bin/validatepem.py $(pwd)/tomcat.pem

[ $? -eq 0 ] || exiterror "Your certificate has issues. Is the private key included (and without a passphrase)?"

cat <<EOB > $(pwd)/ssl.conf
\$SERVER["socket"] == "0.0.0.0:443" {
    ssl.engine                  = "enable"
    ssl.pemfile                 = "${SSLDIR}/tomcat.pem"
}
EOB

	authd makedir ${SSLDIR}
	authd installfile tomcat.pem ${SSLDIR}
	authd installfile ssl.conf ${LIGHTTPDIR}

	restart_lighttpd
}

HTTPS.update() {
    HTTPS.create
}


Module.getconfig() {

  cat << _EOF_
  <openpanel.module>
    <dict id="TomcatAdmin" type="class">
      <dict id="Admin">
	    <string id="password">*</string>
      </dict>
    </dict>
  </openpanel.module>
_EOF_
  exitquiet
}

restart_tomcat() {
	authd reloadservice tomcat6
}

restart_lighttpd() {
	authd reloadservice lighttpd
}

implement OpenAppTomcat.module
